kind: Service
apiVersion: v1
metadata:
  name: vtgate-{{.Cell}}
  labels:
    component: vtgate
    cell: {{.Cell}}
    app: vitess
spec:
  ports:
    - name: web
      port: 15001
    - name: grpc
      port: 15991
    - name: mysql
      port: {{.MysqlServerPort}}
  selector:
    component: vtgate
    cell: {{.Cell}}
    app: vitess
  type: LoadBalancer
