kind: Service
apiVersion: v1
metadata:
  name: mole
  labels:
    component: api
    app: mole
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    component: api
    app: mole
  type: LoadBalancer

