kind: Service
apiVersion: v1
metadata:
  name: mole
  labels:
    component: api
    app: mole
  annotations:
    jdos.jd.com/maxconnect: "10240"
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    component: api
    app: mole
  type: ClusterIP
