kind: Service
apiVersion: v1
metadata:
  name: mole
  labels:
    component: api
    app: mole
spec:
  ports:
    - port: 80
      targetPort: api-server
  selector:
    component: api
    app: mole
  type: LoadBalancer

