kind: Pod
apiVersion: v1
metadata:
  name: vttablet-{{.Uid}}
  labels:
    component: vttablet
    keyspace: "{{.Keyspace}}"
    shard: "{{.ShardLabel}}"
    tablet: "{{.Alias}}"
    app: vitess
spec:
  containers:
    - name: vttablet
      image: vitess/root
      resources:
        limits:
          memory: "4Gi"
          cpu: "2"
      volumeMounts:
        - name: syslog
          mountPath: /dev/log
        - name: vtdataroot
          mountPath: /vt/vtdataroot
      command:
        - bash
        - "-c"
        - >-
          set -e

          mysql_socket="$VTDATAROOT/{{.TabletSubdir}}/mysql.sock"

          mkdir -p $VTDATAROOT/tmp

          chown -R vitess /vt

          while [ ! -e $mysql_socket ]; do
          echo "[$(date)] waiting for $mysql_socket" ;
          sleep 1 ;
          done

          su -p -s /bin/bash -c "mysql -u vt_dba -S $mysql_socket
          -e 'CREATE DATABASE IF NOT EXISTS vt_{{.Keyspace}}'" vitess

          su -p -s /bin/bash -c "/vt/bin/vttablet
          -topo_implementation etcd
          -etcd_global_addrs http://etcd-global:4001
          -log_dir $VTDATAROOT/tmp
          -alsologtostderr
          -port {{.Port}}
          -grpc_port {{.GrpcPort}}
          -service_map 'grpc-queryservice,grpc-tabletmanager,grpc-updatestream'
          -tablet-path {{.Alias}}
          -tablet_hostname $(hostname -i)
          -init_keyspace {{.Keyspace}}
          -init_shard {{.Shard}}
          -init_tablet_type {{.TabletType}}
          -mysqlctl_socket $VTDATAROOT/mysqlctl.sock
          -db-config-app-uname vt_app
          -db-config-app-dbname vt_{{.Keyspace}}
          -db-config-app-charset utf8
          -db-config-dba-uname vt_dba
          -db-config-dba-dbname vt_{{.Keyspace}}
          -db-config-dba-charset utf8
          -db-config-repl-uname vt_repl
          -db-config-repl-dbname vt_{{.Keyspace}}
          -db-config-repl-charset utf8
          -db-config-filtered-uname vt_filtered
          -db-config-filtered-dbname vt_{{.Keyspace}}
          -db-config-filtered-charset utf8
          -queryserver-config-transaction-cap 300
          -queryserver-config-schema-reload-time 1
          -queryserver-config-pool-size 100
          -enable_replication_reporter" vitess
      env:
        - name: GOMAXPROCS
          value: "16"
    - name: mysql
      image: vitess/root
      resources:
        limits:
          memory: "4Gi"
          cpu: "2"
      volumeMounts:
        - name: syslog
          mountPath: /dev/log
        - name: vtdataroot
          mountPath: /vt/vtdataroot
      command:
        - sh
        - "-c"
        - >-
          mkdir -p $VTDATAROOT/tmp &&
          chown -R vitess /vt

          su -p -c "/vt/bin/mysqlctld
          -log_dir $VTDATAROOT/tmp
          -alsologtostderr
          -tablet_uid {{.Uid}}
          -socket_file $VTDATAROOT/mysqlctl.sock
          -db-config-dba-uname vt_dba
          -db-config-dba-charset utf8
          -init_db_sql_file $VTROOT/config/init_db.sql" vitess
      env:
        - name: EXTRA_MY_CNF
          value: /vt/config/mycnf/benchmark.cnf:/vt/config/mycnf/master_mysql56.cnf
  volumes:
    - name: syslog
      hostPath: {path: /dev/log}
    - name: vtdataroot
      {{.VtdatarootVolume}}
