kind: ReplicationController
apiVersion: v1
metadata:
  name: vtgate-{{.Cell}}
spec:
  replicas: {{.Replicas}}
  template:
    metadata:
      labels:
        component: vtgate
        cell: {{.Cell}}
        app: vitess
    spec:
      containers:
        - name: vtgate
          image: {{.VitessImage}}
          livenessProbe:
            httpGet:
              path: /debug/vars
              port: 15001
            initialDelaySeconds: 30
            timeoutSeconds: 5
          volumeMounts:
            - name: syslog
              mountPath: /dev/log
            - name: vtdataroot
              mountPath: /vt/vtdataroot
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          command:
            - sh
            - "-c"
            - >-
              mkdir -p $VTDATAROOT/tmp &&
              chown -R vitess /vt &&
              su -p -c "/vt/bin/vtgate
              -topo_implementation etcd
              -etcd_global_addrs http://etcd-global:4001
              -log_dir $VTDATAROOT/tmp
              -alsologtostderr
              -port 15001
              -grpc_port 15991
              -mysql_server_port {{.MysqlServerPort}}
              -mysql_auth_server_config_string '{\"mysql_user\":{\"Password\":\"mysql_password\"}}'
              -service_map 'grpc-vtgateservice'
              -cells_to_watch {{.Cell}}
              -tablet_types_to_wait MASTER,REPLICA
              -gateway_implementation discoverygateway
              -cell {{.Cell}}" vitess
      volumes:
        - name: syslog
          hostPath: {path: /dev/log}
        - name: vtdataroot
          emptyDir: {}
