# Regular service for load balancing client connections.
kind: Service
apiVersion: v1
metadata:
  name: etcd-{{.Cell}}
  labels:
    component: etcd
    cell: {{.Cell}}
    app: vitess
spec:
  ports:
    - port: 4001
  selector:
    component: etcd
    cell: {{.Cell}}
    app: vitess
